Adding option to run bootstrap with local copy
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #287
Opened 2022-05-19 12:31 UTC by eifrach

Signed-off-by: eifrach <eifrach@redhat.com>

# Description

* adding option to run a local copy of `bootstrap.sh`  

Fixes #282 

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

2022-05-19 16:05 UTC, flaper87 requested changes
Close enough! This will be useful for local-development and branches.

2022-05-19 16:05 UTC, flaper87 commented on pipelines/bootstrap.sh
> +if [[ "${0}" == *"bootstrap.sh" ]]; then
I think you want to use something like: 

`SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )`

`${0}` is not guaranteed to be `bootstrap.sh` if you run `bash bootstrap.sh` or in some other form

2022-05-19 16:05 UTC, flaper87 commented on pipelines/bootstrap.sh
> +    if [[ $PWD == *'pipelines' ]]; then
The suggested edit above should give you the path to the bootstrap.sh, from there you can use relative paths to build the `PIPELINES_DIR`

2022-05-23 09:25 UTC, eifrach commented on pipelines/bootstrap.sh
> +if [[ ${@} == *'clean'* ]]; then
@flaper87 i had to add this change

when running locally the clean is on $1 
when running remote its on $2

2022-05-25 04:32 UTC, alknopfler commented
Please @eifrach when we finish to fix the issue with the mirror, rebase this and pass the check before merge it.

2022-05-25 11:01 UTC, eifrach commented
@alknopfler @flaper87 
tested  and rebased to `main`

2022-05-30 09:17 UTC, alknopfler commented
@eifrach please could you verify if the make file which invoke the bootstrap script should be modified also?
I think if the script is expecting a new param, should be modified also in the makefile

2022-05-30 09:30 UTC, alknopfler commented
LGTM

2022-06-10 11:52 UTC, flaper87 approved these changes
/lgtm

2022-06-13 09:06 UTC, merged

2022-06-15 07:53 UTC, iranzo commented
:tada: This PR is included in version 1.9.1 :tada:

The release is available on [GitHub release](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/releases/tag/1.9.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: