removing "error" from informational messages
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #307
Opened 2022-05-26 11:41 UTC by eifrach

Signed-off-by: Eran Ifrach <eifrach@redhat.com>

# Description

* Change all informational message from `ERROR` to `INFO` 
FIX #302

 * change wget to curl
 FIX #306

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

2022-05-26 14:28 UTC, iranzo requested changes
lgtm, just the nit

2022-05-26 14:28 UTC, iranzo commented on deploy-disconnected-registry/olm-sync.sh
> +            echo ">>>> INFO: Failed runing index image: ${OLM_DESTINATION_INDEX}"
missing 'p' in pruning

2022-05-26 16:54 UTC, iranzo approved these changes
LGTM!

2022-05-30 09:33 UTC, alknopfler commented
@eifrach could you test ci? after updating branch? I don't know why first time test didn't launch, but if not, just switch off/on the test-ci label

2022-06-01 10:51 UTC, merged

2022-06-02 14:46 UTC, iranzo commented
:tada: This PR is included in version 1.8.3 :tada:

The release is available on [GitHub release](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/releases/tag/1.8.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: