Pr logrotate
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #310
Opened 2022-05-27 02:16 UTC by DirectedSoul1

# Description

This PR uses `logrotate` using cron to compress all larger files > 5MiB from `/var/log/messages` 

## Type of change

Please select the appropriate options:

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have performed a self-review of my own code
- [x] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [x] PRs should not be merged unless positively reviewed.

2022-05-30 06:45 UTC, iranzo commented
I think that changelog should be left out of the PR, as it is managed entirely by the release GHA

2022-05-30 08:40 UTC, fbac requested changes
Hey shashank o/

I added a couple comments, also please take a look at setup.yaml, as in the finalizing task you'll have to include the added labels, so it's executed whatever the label you're running the playbook with.

```
    - name: Finalize playbook
      include_tasks: tasks/finalizers/99-finalizers.yaml
      tags: [ 00-base-os, 00-base-network, 01-packages, 
            01-configure-dnf, 02-bin-utils, 
            00-common-services, configure-sshd,
            configure-tuned, configure-chronyd,
            configure-logrotate, configure-libvirtd ]
```

2022-05-30 08:40 UTC, fbac commented on hack/deploy-hub-local/ansible/setup.yaml
> +    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
I would leave all the ssh related actions inside the ssh subdirectory, and with the same tag used currently, so we can force/skip it whenever needed.
Also maybe add some vars? For example forcing a certain key type, key length, etc.

2022-05-30 08:40 UTC, fbac commented on hack/deploy-hub-local/ansible/setup.yaml
> +    - name: Install logrotate
Same as with sshd actions, for logrotate maybe creating a subdirectory for all its specific actions its more convenient, and all of them using a common tag such as [configure-logrotate] using the same name convention.

2022-05-30 08:40 UTC, fbac commented on hack/deploy-hub-local/ansible/setup.yaml
> +    - name: Add Slack notifications
Not sure about this task regarding recent discussions, probably we'll have to leave it out of the playbooks until we figure the way we want to be notified about the server statuses.

2022-05-31 13:54 UTC, fbac commented
I'll be closing this PR as I'm assigning to myself this task to liberate shegde. The work will be resumed in some time.

2022-05-31 13:54 UTC, closed without merging