Verify ocs and spoke sync
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #35
Opened 2021-12-14 13:31 UTC by alknopfler

- verify in ocs step
- verify for registry sync into spokes: verify, verify_ocp_sync and verify_olm_sync

2021-12-14 15:18 UTC, jparrill requested changes

2021-12-14 15:18 UTC, jparrill commented on deploy-ocs/verify.sh
> +	echo ">>>> Deploy manifests to install LSO and LocalVolume: ${spoke}"
Change the message to match a verification :D

2021-12-14 15:18 UTC, jparrill commented on deploy-ocs/verify.sh
> +
We need to add some verifications here:
- For LSO: PVs and Running Pods
- For OCS: StorageClasses available and Running pods

2021-12-14 15:55 UTC, alknopfler reviewed
LGTM

2021-12-14 15:55 UTC, jparrill approved these changes

2021-12-14 15:55 UTC, jparrill commented
LGTM

2021-12-14 15:55 UTC, merged

2021-12-23 08:14 UTC, iranzo commented
:tada: This PR is included in version 0.0.5 :tada:

The release is available on [GitHub release](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/releases/tag/0.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: