fix: remove unneeded cluster index
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #414
Opened 2022-06-15 13:45 UTC by iranzo

# Description

Remove cluster indexes that seem not to be required

Fixes #132

2022-06-16 14:47 UTC, iranzo commented
https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/runs/6902700105?check_suite_focus=true

2022-06-16 15:49 UTC, fbac approved these changes
LGTM

2022-06-21 10:50 UTC, alknopfler commented
Could I ask why index will not be required ??? just for curiosity...

2022-06-21 10:51 UTC, iranzo commented
Sure, check the linked issue where you can see the commands that return exactly the same result

2022-06-21 10:55 UTC, alknopfler commented
> Sure, check the linked issue where you can see the commands that return exactly the same result

mmm but what happens if we have 2 or more clusters in the config yaml file? TBH even maybe could be the same result, I don't feel comfortable changing this because this info of cluster could be useful in the future to log for example the name in a easy way....I'd like having this in case we need to refer the cluster name in the future or maybe to make it clear ... 
WDYT???

2022-06-21 10:57 UTC, iranzo commented
> > Sure, check the linked issue where you can see the commands that return exactly the same result
> 
> mmm but what happens if we have 2 or more clusters in the config yaml file? TBH even maybe could be the same result, I don't feel comfortable changing this because this info of cluster could be useful in the future to log for example the name in an easy way....I'd like having this in case we need to refer the cluster name in the future or maybe to make it clear ... WDYT???

The 'more than one' cluster is handled via the '${index}' part in the command as it directly branches from the main '.spokes' section, not from within a cluster itself

2022-06-21 11:14 UTC, eifrach commented on deploy-edgecluster/render_edgeclusters.sh
> +        export CHANGE_EDGE_MASTER_PUB_INT=$(yq eval ".edgeclusters[${edgeclusternumber}].[].master${master}.nic_int_static" ${EDGECLUSTERS_FILE})
maybe i have it wrong but i cannot find the list '[]' in the yaml 
```console
$ yq e ".edgeclusters[0].[].master0" examples/config.yaml
Error: Bad expression, please check expression syntax
```
it looks like a dict so this syntx should not work
```shell
yq e ".edgeclusters[0].edgecluster1-name.master0" examples/config.yaml
ignore_ifaces: eno1 eno2
nic_ext_dhcp: eno4 # ext_dhcp -> DHCP
mac_ext_dhcp: "aa:ss:dd:ee:b0:10"
bmc_url: "<url bmc>"
bmc_user: "user-bmc" #TODO  may be clear test and render with script
bmc_pass: "user-pass" #TODO  may be clear test and render with script
root_disk: "/dev/sda"
storage_disk:
  - /dev/sdb
  - /dev/sdc
  - /dev/sde
  - /dev/sdd
  ````

2022-06-26 10:20 UTC, eifrach requested changes
hey since this requires a newer version of YQ 
let's bump fist the version on the repo
PR #447

2022-06-27 06:21 UTC, iranzo commented
> hey since this requires a newer version of YQ let's bump fist the version on the repo PR #447

Not really sure as it already passed the CI tests with the previous version at https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/runs/6902700105?check_suite_focus=true

2022-06-27 06:25 UTC, eifrach commented
> > hey since this requires a newer version of YQ let's bump fist the version on the repo PR #447
> 
> Not really sure as it already passed the CI tests with the previous version at https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/runs/6902700105?check_suite_focus=true

On the host version it was not updated. The container version is supporting this change

But for good measure we shold bump it

2022-07-04 09:14 UTC, eifrach commented
lgtm

2022-07-04 10:00 UTC, merged

2022-07-04 10:02 UTC, iranzo commented
:tada: This PR is included in version 1.10.1 :tada:

The release is available on [GitHub release](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/releases/tag/1.10.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: