adding monitor for quay operator deployment
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #505
Opened 2022-07-27 12:42 UTC by eifrach

Signed-off-by: Eran Ifrach <eifrach@redhat.com>

# Description

Adding monitor for quay deployment instead of waiting 30 sec
in some cases, deployment will take more then 30 sec 

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

2022-07-27 12:50 UTC, iranzo requested changes

2022-07-27 12:50 UTC, iranzo commented on deploy-disconnected-registry/deploy.sh
> +		echo "INFO: waiting for Quay Operator to be ready ( 1 min )"
mixed tabs and spaces for identation

2022-07-28 08:58 UTC, iranzo approved these changes
lgtm

2022-07-28 10:54 UTC, flaper87 commented on deploy-disconnected-registry/deploy.sh
> +		echo "INFO: waiting for Quay Operator to be ready ( 1 min )"
1min sounds like too little. Can we do a 2min or 3 max?

2022-07-28 13:13 UTC, alknopfler reviewed
LGTM let's test it ok?

2022-08-09 13:22 UTC, flaper87 approved these changes

2022-08-09 14:36 UTC, merged