MGMT-10891: Rephrase Custom Domain page
rh-ecosystem-edge/ztp-pipeline-relocatable pull request #509
Opened 2022-07-28 09:08 UTC by mareklibra

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

2022-07-28 10:51 UTC, flaper87 requested changes
small wording nit, otherwise LGTM

(let's change all the `root` domain wth `base domain`, which aligns better with OCP terminology

2022-07-28 10:51 UTC, flaper87 commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainPage.test.tsx.snap
> +               Enter the name of root domain for your edge cluster (e.g. yourdomain.com)
```suggestion
               Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-28 13:08 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
> +       Enter the name of root domain for your edge cluster (e.g. yourdomain.com)
```suggestion
       Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-28 13:08 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
> +       Enter the name of root domain for your edge cluster (e.g. yourdomain.com)
```suggestion
       Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-28 13:08 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
> +       Enter the name of root domain for your edge cluster (e.g. yourdomain.com)
```suggestion
       Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-31 11:51 UTC, eifrach requested changes

2022-07-31 11:51 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainPage.test.tsx.snap
> +               Enter the name of baseu domain for your edge cluster (e.g. yourdomain.com)
mistype
```suggestion
               Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-31 11:51 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
> +       Enter the name of baseu domain for your edge cluster (e.g. yourdomain.com)
```suggestion
       Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-31 11:51 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
> +       Enter the name of baseu domain for your edge cluster (e.g. yourdomain.com)
```suggestion
       Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-31 11:51 UTC, eifrach commented on ui/frontend/src/components/DomainPage/__snapshots__/DomainSelector.test.tsx.snap
> +       Enter the name of baseu domain for your edge cluster (e.g. yourdomain.com)
```suggestion
       Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-07-31 11:51 UTC, eifrach commented on ui/frontend/src/components/DomainPage/DomainSelector.tsx
> +        <OptionalBadge /> Enter the name of baseu domain for your edge cluster (e.g. yourdomain.com)
```suggestion
        <OptionalBadge /> Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
```

2022-08-01 07:29 UTC, eifrach approved these changes

2022-08-01 07:29 UTC, mareklibra commented on ui/frontend/src/components/DomainPage/DomainSelector.tsx
> +        <OptionalBadge /> Enter the name of baseu domain for your edge cluster (e.g. yourdomain.com)
Ooops, thanks.

2022-08-01 07:32 UTC, merged

2022-08-01 07:39 UTC, alknopfler reviewed
LGTM